# serverless.yml

service: Serverless-Spine-Express

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  vpc:
      securityGroupIds:
        - sg-here
      subnetIds:
        - subnet-here

plugins:
  - serverless-offline

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'