# serverless.yml

service: External-Journal

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-east-1
  vpc:
      securityGroupIds:
        - sg-618f7f1a
      subnetIds:
        - subnet-aee38bcb
        - subnet-10b0ec2d
        - subnet-f45e31ac
        - subnet-178d191b
        - subnet-21451557
        - subnet-ddcea8f7

plugins:
  - serverless-offline

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'